version: '3.2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      # There is only one es node.
      discovery.type: "single-node"
      node.name: "elasticsearch"
      cluster.name: "es-docker-cluster"
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - /usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    ports:
      - "5601:5601"
    environment:
      server.name: kibana
      server.host: 0.0.0.0
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - elastic
    depends_on:
      - elasticsearch

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - 3380:3306
    environment:
      - MYSQL_DATABASE=movie_db
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=Test_Pass_1
      - MYSQL_ROOT_PASSWORD=Root_Pass_1
    volumes:
      - ./docker-configs/mysql/conf.d:/etc/mysql/conf.d
      - ./dataset/ml-100k/u.item:/var/lib/mysql-files/u.item
      - ./docker-configs/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.2
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    volumes:
      - ./dataset/access.log:/dataset/access.log
      - ./plugins/mysql-connector-java-8.0.21:/plugins/mysql-connector-java-8.0.21
      - ./docker-configs/logstash/pipeline:/usr/share/logstash/pipeline
      - ./docker-configs/logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
    # command: bin/logstash -f /usr/share/logstash/pipeline/logstash.conf
    command: --config.reload.automatic
    environment:
      http.host: "0.0.0.0"
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
    networks:
      - elastic
    depends_on:
      - elasticsearch
      - mysql

networks:
  elastic:
    driver: bridge